### ISSUE TITLE
Project contributions inclarity

### ISSUE THREAD

**Issue by msueberkrueb** [dclausen01/bbz-cloud-sus#1]
Hi,
to allow for a thriving project with many contributers the following questions should be publicly answered:

Is this project open to contributions? If so:
- where can I find open issues or a roadmap with planned features?
- how can and should I contribute these issues?

**Comment by dclausen01** [comment]
Hi Mike,

nice to have you on board! 😊 Contributions are very welcome! Our base repo is located at https://github.com/koyuawsmbrtn/bbz-cloud - that's where the magic happens. This repo is just for the sus-version which is derived from the repo mentioned above.
At the moment I'm fighting with desktopCapturer for implementing screensharing (see branch screensharing).

Dennis

Sent from Nine<http://www.9folders.com/>

________________________________
Von: Mike Süberkrüb ***@***.***>
Gesendet: Montag, 29. August 2022 15:17
An: dclausen01/bbz-cloud-sus
Cc: Subscribed
Betreff: [dclausen01/bbz-cloud-sus] Project contributions inclarity (Issue #1)


Hi,
to allow for a thriving project with many contributers the following questions should be publicly answered:

Is this project open to contributions? If so:

  *   where can I find open issues or a roadmap with planned features?
  *   how can and should I contribute these issues?

**Comment by msueberkrueb** [comment]
Hi Dennis,
would it be possible to add this information in the readme, so others aren't as confused as I were?

LG Mike

**Comment by koyuawsmbrtn** [comment]
Fixed 2d8f3cad76d792e2efee928cd8dcde833488343e
